spring:
  application:
    name: authentication-service
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: ${SERVER-PORT:8081}

jwt:
  signerKey: 1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true

multi-tenancy:
  common:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://${MYSQL_URL:localhost:3306/spring_common}?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
      username: ${MYSQL_USERNAME:root}
      password: ${MYSQL_PASSWORD:123456}
      maximum-pool-size: 10
  tenant:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 10