server:
  port: ${SERVER-PORT:8085}

spring:
  application:
    name: migration
  datasource:
    url: jdbc:mysql://${MYSQL_URL:localhost:3306/spring_common}?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:123456}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

multi-tenancy:
  master:
    liquibase:
      enabled: true
      drop-first: false #never set true on production
      change-log: classpath:db/changelog/db.changelog-master.yaml
  tenant: #specfic config for each tenant datasource
    liquibase:
      enabled: true
      drop-first: false #never set true on production
      changeLog: classpath:db/changelog/db.changelog-tenant.yaml

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true