spring:
  application:
    name: discovery

server:
  port: 8761

eureka:
  instance:
    hostname: ${SERVER_HOSTNAME:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:${server.port}/eureka/}